name: aeronaves.csv

on: [push]

jobs:
  download-csv:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Aeronaves
      run: |
        mkdir -p data
        wget -r -np -nH --cut-dirs=3 -A .csv https://raw.githubusercontent.com/gabrielmacedoanac/flat-data-anac/main/aeronaves.csv -P data
        wget -r -np -nH --cut-dirs=3 -A .csv https://raw.githubusercontent.com/gabrielmacedoanac/flat-data-anac/main/drones.csv -P data
