on:
  schedule:
    - cron: "0 1 * * *"

jobs:
  build:
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          repository: gabrielmacedoanac/flat-data-anac

      - name: Find .csv and .json files
        run: |
          find . -name "*.csv" -o -name "*.json" > file_list.txt

      - name: Copy files to current repository
        run: |
          xargs -a file_list.txt cp -t .
